### ISSUE TITLE
Akka HTTP

### ISSUE THREAD

**Issue by spangaer** [mdedetrich/akka-apache-project#6]
I know, learn to walk before your run etc, but can we onboard Akka HTTP in to the same project?

I guess it's not used inside Flink, but I'm guessing quite a bit of the greater Akka community does make use of it. It will often be our primary 'attack surface', so hard to go without.

I don't think the Git project needs to be re-united (wouldn't mind either), as they have been split to allow them to have separate release cycles. But having a single governing body for both would be a good thing.

**Comment by He-Pin** [comment]
I think this project is just a meta holder, so Akka HTTP would be included too.

**Comment by spangaer** [comment]
For now I'm just going to leave this issue open so others can easily find it.

**Comment by mdedetrich** [comment]
It is also intended to support akka-http, I am going to be renaming this project to indicate its meant to be a meta project for all other projects.

**Comment by mdedetrich** [comment]
Closing the issue, this repo has been renamed to `akka-apache-project` and it contains git submodules of every other akka project (including akka-http).
